controller_list:
  - name: fake_end_effector_controller
    joints:
      []
  - name: fake_arm_controller
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
  - name: fake_base_controller
    joints:
      - joint0